### ISSUE TITLE
Set up basic Express application

### ISSUE THREAD

**Issue by evamcconville** [SchoolOfCode/bc17-w4d2-project-teamsapranos#1]
```[tasklist]
### Tasks
- [x] Install express
- [ ] Create readme
- [x] Set adress “http://localhost:3000/”
- [x] Response includes status code 200
- [x] Responce includes string "something mafia related"
```
