### ISSUE TITLE
Implement functionality to GET all activities for a particular user

### ISSUE THREAD

**Issue by evamcconville** [SchoolOfCode/bc17-w4d2-project-teamsapranos#3]
```[tasklist]
### Tasks
- [ ] specify user ID at endpoint
- [x] create JSON for data that includes
- [x] check GET request linked to port
- [x] Try
- [x] response data activity objects
- [x] status code for success
- [x] catch
- [x] status code for failure
```
