### ISSUE TITLE
Implement functionality to POST a new activity

### ISSUE THREAD

**Issue by evamcconville** [SchoolOfCode/bc17-w4d2-project-teamsapranos#4]
```[tasklist]
### Tasks
- [x] make requested activity into const
- [x] use an if to check an activity is acually requested
- [x] imoprt id makey middleware
- [x] create new const to combine added activity with a time
- [ ] push added activity to data file
- [ ] json reading middleware
```
